### ISSUE TITLE
Unlocked package now working

### ISSUE THREAD

**Issue by ahamed-WK** [trailheadapps/lwc-recipes#560] opened 2021-09-01 05:41 UTC
### Summary

Error displayed when installing app through Unlocked package

### Steps To Reproduce:

1. install the LWC recipes app using the unlocked package

### Expected result

App should be deployed

### Actual result

Displayed error and not getting installed 

### Additional information

_Feel free to attach a screenshot or code snippets_.
![image](https://user-images.githubusercontent.com/64770936/131617843-c5e070f1-9631-4217-a36b-6bcaf53ddb21.png)

**Comment by satyasekharcvb** [comment] 2021-09-01 09:58
Hi @ahamed-WK , We are unable to reproduce the error and it is working for me. Are you still facing the issue? If so, please let us know.

**Comment by ahamed-WK** [comment] 2021-09-01 10:32
I tried in the morning i was facing the issue
Let me try it out in sometime see if its still reproduce same

**Comment by ahamed-WK** [comment] 2021-09-01 10:37
@satyasekharcvb still same
![image](https://user-images.githubusercontent.com/64770936/131657400-8e3caf20-8e95-4bf2-a435-213d0bc2e217.png)

**Comment by msrivastav13** [comment] 2021-09-01 13:20
@ahamed-WK Could you verify that you have a class with name 'Test' or 'test' in your org where you are installing? This could potential cause the issue.

**Comment by ahamed-WK** [comment] 2021-09-01 14:17
@msrivastav13 im compiling only the package the file why is that considering the other apex class which are existing

**Comment by msrivastav13** [comment] 2021-09-01 20:54
@ahamed-WK In unlocked package,it does considers whats there in org. Its not a managed package to be in a namespace.

Could you let us know if that was the case and you had a class named Test? If yes, we can close this.

**Closed** 2021-09-02 02:39 UTC
