### ISSUE TITLE
Code Tour doesn't run

### ISSUE THREAD

**Issue by benji1304** [trailheadapps/lwc-recipes#712] opened 2022-08-03 08:48 UTC
### Summary

I've got the Code Tour extension installed but re-opening the LWC rep or command palette > Open Tour doesnt get it to start.

I see it in the Explorer tab but it just doesn't do anything? 

![image](https://user-images.githubusercontent.com/7213889/182565850-18e3a383-d6ca-4873-8023-3188b7995bfd.png)

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

1. Follow instructions to clone lwc-recipes locally
2. Install Code Tour extension
3. Restart VS Code
4. Reopen local repo

### Current Behavior

No code tour runs

### Expected Behavior

Code tour runs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment] 2022-08-03 15:55
Hi @benji1304,
You can click the triangle next to  Welcome to LWC Recipes in the CODE TOUR tab. It launches the tour and you can click the next button to navigate through the tour. It is working as expected
![codeTour](https://user-images.githubusercontent.com/31529847/182654020-9c10df3d-add2-42f5-a4e7-51f644743692.gif)
.

**Comment by benji1304** [comment] 2022-08-03 20:06
Thanks @satyasekharcvb, unfortunately I'm not seeing that triangle play button on my code tour tab

![image](https://user-images.githubusercontent.com/7213889/182699219-9274fa40-e931-47c5-bddf-2aeabba183ec.png)

**Comment by satyasekharcvb** [comment] 2022-08-04 03:26
Hi @benji1304,
Can you try clicking the up arrow and down arrow on the right in your screenshot and see if it navigates? Also, check if you can run the **CodeTour: Start Tour** command from the command palette. If not, please uninstall the code tour and reinstall it. Also, make sure you run **Developer: Reload Window**  from the command palette after uninstalling and reinstalling.

**Comment by benji1304** [comment] 2022-08-04 03:42
The up and down arrows move the items around in the list
![image](https://user-images.githubusercontent.com/7213889/182758047-8350677f-f7bc-402e-8c87-22f8e7e0ce34.png)

I don't have the option of Start Tour
![image](https://user-images.githubusercontent.com/7213889/182758069-b7eaaf7b-ec7b-41af-9b37-7c2d56e2d111.png)

If I click Resume Tour nothing happens.

I can see Code Tour in the Extension Host log
`[2022-08-03 20:38:46.520] [exthost] [info] ExtensionService#_doActivateExtension vsls-contrib.codetour, startup: true, activationEvent: '*'` 

I can try logging this into https://github.com/microsoft/codetour too

**Comment by satyasekharcvb** [comment] 2022-10-11 03:36
Closing this as the issue is with the plugin. Please let us know if you still face the problem.

**Closed by satyasekharcvb** 2022-10-11 03:36 UTC
Labels: bug
