### ISSUE TITLE
Installing Recipes using an Unlocked Package doesn't show all the components

### ISSUE THREAD

**Issue by gouravsood** [trailheadapps/lwc-recipes#140] opened 2019-10-03 03:39 UTC
### Summary

Following the Steps as mentioned in the readme for Installing Recipes using an Unlocked Package doesn't show all the functionality. 

### Steps To Reproduce:

After completing all steps as per "Installing Recipes using an Unlocked Package" section, none of the components are shown. 

![image](https://user-images.githubusercontent.com/4436378/66097762-04a88280-e5e3-11e9-935f-15c92d34b11b.png)

I have tried following the steps mentioned Installing Recipes using a Scratch Org and that works as expected

### Expected result

Should show all LWC Components

### Actual result

Cannot see LWC Components

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by pchittum** [comment] 2019-10-09 09:24
Hi @gouravsood. I'm looking into this to see if I can reproduce the problem.

**Comment by pchittum** [comment] 2019-10-09 09:38
After following the entire set of instructions for installation via unlocked package, the installation was successful. 

Can you verify you completed all the steps for installation? 

If you stop immediately after package installation, and don't complete the remaining steps you won't see the recipe cards.

**Comment by gouravsood** [comment] 2019-10-09 23:53
Hi @pchittum I did follow & completed all the 7 steps as per the documentation but it wasn't working. 

When I followed the scratch org approach, then it worked as expected.

**Comment by v-shankar01** [comment] 2019-10-18 18:24
Hi @gouravsood,

Please check whether 'My Domain' is enabled and deployed to Users. I faced the same issue and deploying the domain solved the issue. Please check.

@pchittum - FYI.

Regards,
Shankar

**Comment by gouravsood** [comment] 2019-10-20 00:31
@v-shankar01 as mentioned in the description of this issue, I have followed all the steps as per the documentation and setting my domain was step 2. But still I cannot see the components loading:

![image](https://user-images.githubusercontent.com/4436378/67152982-1309d480-f32d-11e9-8437-1ba8046dabcf.png)

**Comment by JoeyOgalesco** [comment] 2019-12-19 14:41
Setup -> My Domain -> "Deploy to Users"

**Comment by pchittum** [comment] 2019-12-20 08:30
@gouravsood, thanks for posting this. I'm unable to reproduce after two goes on two different DE orgs. You've also verified following all steps. I'm going to close this, but if you find more information to help identify what was the cause of your problem and how to address it in this repo (whether in the code or the docs), feel free to reopen and we'll take it from there.

**Closed by pchittum** 2019-12-20 08:30 UTC
