### ISSUE TITLE
Broken Image in the compoenent

### ISSUE THREAD

**Issue by Isthiyaqsforce-P** [trailheadapps/lwc-recipes#420] opened 2020-11-15 07:02 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Open Message Service Tab in the LWC Recipes App
2.  Click on the any name displayed in the LmsPublisherVisualforce
3.  Image is not getting displayed in the LmsPublisherVisualforce, LmsSubscriberWebComponent, LmsSubscriberAuraComponent, LmsSubscriberVisualforceRemoting, LmsSubscriberVisualforcePostbackAction

### Expected result

Display the correct image

### Actual result

not displaying the image

### Additional information

![image](https://user-images.githubusercontent.com/73593899/99178945-8fdccd00-273e-11eb-9e65-19727b56e4e1.png)

**Comment by pchittum** [comment] 2020-11-30 11:39
I've observed this happening intermittently. This can be impacted by release and patch activity and is particularly prevalent in pre-release orgs. 

Closing for the moment, as I'm unable to reproduce this. Even after refreshing my scratch org. 

If you can find any specific factors that may be causing this, please fill us in. Thanks!

**Closed** 2020-12-08 00:45 UTC
Labels: no-issue-activity
