### ISSUE TITLE
Installed package error in Spring'19 dev org 

### ISSUE THREAD

**Issue by rsoesemann** [trailheadapps/lwc-recipes#54] opened 2019-02-10 15:09 UTC
Same issue as #47

**Comment by muenzpraeger** [comment] 2019-02-11 14:10
Fixed by #55

**Closed by muenzpraeger** 2019-02-11 14:10 UTC

**Comment by rsoesemann** [comment] 2019-02-12 06:32
#NotFixed Please reopen. Installing the package from the link failed with 

```
Package: LWCRecipes (04tB0000000KAfT)
Error Number: 692877099-3564 (1334909473)
Problem:

1. (recipes) In field: field - no CustomField named Contact.CleanStatus found
recipes: In field: field - no CustomField named Contact.CleanStatus found
```

**Comment by muenzpraeger** [comment] 2019-02-12 08:51
Not re-opening as the root cause for this error isn't in the package, but that the DE edition isn't created via the outlined process in the README.
